/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatarConteudoRouteImport } from './routes/relatar-conteudo'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PostarRouteImport } from './routes/postar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ConsultoriaRouteImport } from './routes/consultoria'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvalieSeuSetupRouteImport } from './routes/avalie-seu-setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as SetupSlugRouteImport } from './routes/setup.$slug'
import { Route as MarketplaceAnunciarRouteImport } from './routes/marketplace.anunciar'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as DashboardAfiliadosRouteImport } from './routes/dashboard.afiliados'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatarConteudoRoute = RelatarConteudoRouteImport.update({
  id: '/relatar-conteudo',
  path: '/relatar-conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PostarRoute = PostarRouteImport.update({
  id: '/postar',
  path: '/postar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultoriaRoute = ConsultoriaRouteImport.update({
  id: '/consultoria',
  path: '/consultoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvalieSeuSetupRoute = AvalieSeuSetupRouteImport.update({
  id: '/avalie-seu-setup',
  path: '/avalie-seu-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSlugRoute = SetupSlugRouteImport.update({
  id: '/setup/$slug',
  path: '/setup/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceAnunciarRoute = MarketplaceAnunciarRouteImport.update({
  id: '/marketplace/anunciar',
  path: '/marketplace/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAfiliadosRoute = DashboardAfiliadosRouteImport.update({
  id: '/dashboard/afiliados',
  path: '/dashboard/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/avalie-seu-setup': typeof AvalieSeuSetupRoute
  '/blog': typeof BlogRouteWithChildren
  '/comparar': typeof CompararRoute
  '/comunidade': typeof ComunidadeRoute
  '/consultoria': typeof ConsultoriaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/favoritos': typeof FavoritosRoute
  '/galeria': typeof GaleriaRoute
  '/kits': typeof KitsRoute
  '/orcamento': typeof OrcamentoRoute
  '/perfil': typeof PerfilRoute
  '/postar': typeof PostarRoute
  '/premium': typeof PremiumRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatar-conteudo': typeof RelatarConteudoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/afiliados': typeof DashboardAfiliadosRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/anunciar': typeof MarketplaceAnunciarRoute
  '/setup/$slug': typeof SetupSlugRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/avalie-seu-setup': typeof AvalieSeuSetupRoute
  '/blog': typeof BlogRouteWithChildren
  '/comparar': typeof CompararRoute
  '/comunidade': typeof ComunidadeRoute
  '/consultoria': typeof ConsultoriaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/favoritos': typeof FavoritosRoute
  '/galeria': typeof GaleriaRoute
  '/kits': typeof KitsRoute
  '/orcamento': typeof OrcamentoRoute
  '/perfil': typeof PerfilRoute
  '/postar': typeof PostarRoute
  '/premium': typeof PremiumRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatar-conteudo': typeof RelatarConteudoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/afiliados': typeof DashboardAfiliadosRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/anunciar': typeof MarketplaceAnunciarRoute
  '/setup/$slug': typeof SetupSlugRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/avalie-seu-setup': typeof AvalieSeuSetupRoute
  '/blog': typeof BlogRouteWithChildren
  '/comparar': typeof CompararRoute
  '/comunidade': typeof ComunidadeRoute
  '/consultoria': typeof ConsultoriaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/favoritos': typeof FavoritosRoute
  '/galeria': typeof GaleriaRoute
  '/kits': typeof KitsRoute
  '/orcamento': typeof OrcamentoRoute
  '/perfil': typeof PerfilRoute
  '/postar': typeof PostarRoute
  '/premium': typeof PremiumRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatar-conteudo': typeof RelatarConteudoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/afiliados': typeof DashboardAfiliadosRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/anunciar': typeof MarketplaceAnunciarRoute
  '/setup/$slug': typeof SetupSlugRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avalie-seu-setup'
    | '/blog'
    | '/comparar'
    | '/comunidade'
    | '/consultoria'
    | '/diagnostico'
    | '/favoritos'
    | '/galeria'
    | '/kits'
    | '/orcamento'
    | '/perfil'
    | '/postar'
    | '/premium'
    | '/privacidade'
    | '/relatar-conteudo'
    | '/reset-password'
    | '/termos'
    | '/auth/callback'
    | '/blog/$slug'
    | '/dashboard/admin'
    | '/dashboard/afiliados'
    | '/marketplace/$id'
    | '/marketplace/anunciar'
    | '/setup/$slug'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avalie-seu-setup'
    | '/blog'
    | '/comparar'
    | '/comunidade'
    | '/consultoria'
    | '/diagnostico'
    | '/favoritos'
    | '/galeria'
    | '/kits'
    | '/orcamento'
    | '/perfil'
    | '/postar'
    | '/premium'
    | '/privacidade'
    | '/relatar-conteudo'
    | '/reset-password'
    | '/termos'
    | '/auth/callback'
    | '/blog/$slug'
    | '/dashboard/admin'
    | '/dashboard/afiliados'
    | '/marketplace/$id'
    | '/marketplace/anunciar'
    | '/setup/$slug'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/avalie-seu-setup'
    | '/blog'
    | '/comparar'
    | '/comunidade'
    | '/consultoria'
    | '/diagnostico'
    | '/favoritos'
    | '/galeria'
    | '/kits'
    | '/orcamento'
    | '/perfil'
    | '/postar'
    | '/premium'
    | '/privacidade'
    | '/relatar-conteudo'
    | '/reset-password'
    | '/termos'
    | '/auth/callback'
    | '/blog/$slug'
    | '/dashboard/admin'
    | '/dashboard/afiliados'
    | '/marketplace/$id'
    | '/marketplace/anunciar'
    | '/setup/$slug'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AvalieSeuSetupRoute: typeof AvalieSeuSetupRoute
  BlogRoute: typeof BlogRouteWithChildren
  CompararRoute: typeof CompararRoute
  ComunidadeRoute: typeof ComunidadeRoute
  ConsultoriaRoute: typeof ConsultoriaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  FavoritosRoute: typeof FavoritosRoute
  GaleriaRoute: typeof GaleriaRoute
  KitsRoute: typeof KitsRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PerfilRoute: typeof PerfilRoute
  PostarRoute: typeof PostarRoute
  PremiumRoute: typeof PremiumRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RelatarConteudoRoute: typeof RelatarConteudoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAfiliadosRoute: typeof DashboardAfiliadosRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  MarketplaceAnunciarRoute: typeof MarketplaceAnunciarRoute
  SetupSlugRoute: typeof SetupSlugRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatar-conteudo': {
      id: '/relatar-conteudo'
      path: '/relatar-conteudo'
      fullPath: '/relatar-conteudo'
      preLoaderRoute: typeof RelatarConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postar': {
      id: '/postar'
      path: '/postar'
      fullPath: '/postar'
      preLoaderRoute: typeof PostarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultoria': {
      id: '/consultoria'
      path: '/consultoria'
      fullPath: '/consultoria'
      preLoaderRoute: typeof ConsultoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avalie-seu-setup': {
      id: '/avalie-seu-setup'
      path: '/avalie-seu-setup'
      fullPath: '/avalie-seu-setup'
      preLoaderRoute: typeof AvalieSeuSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$slug': {
      id: '/setup/$slug'
      path: '/setup/$slug'
      fullPath: '/setup/$slug'
      preLoaderRoute: typeof SetupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/anunciar': {
      id: '/marketplace/anunciar'
      path: '/marketplace/anunciar'
      fullPath: '/marketplace/anunciar'
      preLoaderRoute: typeof MarketplaceAnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/afiliados': {
      id: '/dashboard/afiliados'
      path: '/dashboard/afiliados'
      fullPath: '/dashboard/afiliados'
      preLoaderRoute: typeof DashboardAfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AvalieSeuSetupRoute: AvalieSeuSetupRoute,
  BlogRoute: BlogRouteWithChildren,
  CompararRoute: CompararRoute,
  ComunidadeRoute: ComunidadeRoute,
  ConsultoriaRoute: ConsultoriaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  FavoritosRoute: FavoritosRoute,
  GaleriaRoute: GaleriaRoute,
  KitsRoute: KitsRoute,
  OrcamentoRoute: OrcamentoRoute,
  PerfilRoute: PerfilRoute,
  PostarRoute: PostarRoute,
  PremiumRoute: PremiumRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RelatarConteudoRoute: RelatarConteudoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAfiliadosRoute: DashboardAfiliadosRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceAnunciarRoute: MarketplaceAnunciarRoute,
  SetupSlugRoute: SetupSlugRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
