/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostarRouteImport } from './routes/postar'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupSlugRouteImport } from './routes/setup.$slug'

const PostarRoute = PostarRouteImport.update({
  id: '/postar',
  path: '/postar',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSlugRoute = SetupSlugRouteImport.update({
  id: '/setup/$slug',
  path: '/setup/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidade': typeof ComunidadeRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/galeria': typeof GaleriaRoute
  '/orcamento': typeof OrcamentoRoute
  '/postar': typeof PostarRoute
  '/setup/$slug': typeof SetupSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidade': typeof ComunidadeRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/galeria': typeof GaleriaRoute
  '/orcamento': typeof OrcamentoRoute
  '/postar': typeof PostarRoute
  '/setup/$slug': typeof SetupSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidade': typeof ComunidadeRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/galeria': typeof GaleriaRoute
  '/orcamento': typeof OrcamentoRoute
  '/postar': typeof PostarRoute
  '/setup/$slug': typeof SetupSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comunidade'
    | '/diagnostico'
    | '/galeria'
    | '/orcamento'
    | '/postar'
    | '/setup/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comunidade'
    | '/diagnostico'
    | '/galeria'
    | '/orcamento'
    | '/postar'
    | '/setup/$slug'
  id:
    | '__root__'
    | '/'
    | '/comunidade'
    | '/diagnostico'
    | '/galeria'
    | '/orcamento'
    | '/postar'
    | '/setup/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  GaleriaRoute: typeof GaleriaRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PostarRoute: typeof PostarRoute
  SetupSlugRoute: typeof SetupSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/postar': {
      id: '/postar'
      path: '/postar'
      fullPath: '/postar'
      preLoaderRoute: typeof PostarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$slug': {
      id: '/setup/$slug'
      path: '/setup/$slug'
      fullPath: '/setup/$slug'
      preLoaderRoute: typeof SetupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadeRoute: ComunidadeRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  GaleriaRoute: GaleriaRoute,
  OrcamentoRoute: OrcamentoRoute,
  PostarRoute: PostarRoute,
  SetupSlugRoute: SetupSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
